apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-service
  namespace: app-production
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::202516977224:role/sre-portfolio-cluster-api-service-role"
